# from TestObject import TestObject
# from robot.api.logger import info, debug, trace, console

URL = "https://www.saucedemo.com/"
InputName = "id = user-name"
InputPassword = "id = password"
BtnCart = ".shopping_cart_link"
BtnLogin = "id = login-button"
BtnFinish = "id = finish"
BtnCheckout = "id = checkout"
PrtBackpack = "id = add-to-cart-sauce-labs-backpack"
PrtBikeLight = "id = add-to-cart-sauce-labs-bike-light"
PrtBoltTShirt = "id = add-to-cart-sauce-labs-bolt-t-shirt"
PrtFleeceJacket = "id = add-to-cart-sauce-labs-fleece-jacket"
PrtOnesie = "id = add-to-cart-sauce-labs-onesie"
InputFirstName = "id = first-name"
NameFirst = "Ivan"
InputLastName = "id = last-name"
NameLast = "A"
PostalCode = "id = postal-code"
Postal = "20250"
BtnContinue = "id = continue"
FinishTransaction = "id = back-to-products"
ErrorWarning = ".error-message-container"