# from TestObject import TestObject
# from robot.api.logger import info, debug, trace, console

URL = "https://www.saucedemo.com/"

Username1 = "standard_user"
Username2 = "locked_out_user"
Username3 = "problem_user"
Username4 = "performance_glitch_user"
NegativeUsername = "Ivan"
PositivePassword = "secret_sauce"
NegativePassword = "NotAPassword"
NameFirst = "Ivan"
NameLast = "A"
Postal = "20250"

InputName = "id = user-name"
InputPassword = "id = password"
BtnCart = "class = shopping_cart_link"
BtnLogin = "id = login-button"
BtnFinish = "id = finish"
BtnCheckout = "id = checkout"
PrtBackpack = "id = add-to-cart-sauce-labs-backpack"
PrtBikeLight = "id = add-to-cart-sauce-labs-bike-light"
PrtBoltTShirt = "id = add-to-cart-sauce-labs-bolt-t-shirt"
PrtFleeceJacket = "id = add-to-cart-sauce-labs-fleece-jacket"
PrtOnesie = "id = add-to-cart-sauce-labs-onesie"
InputFirstName = "id = first-name"
InputLastName = "id = last-name"
PostalCode = "id = postal-code"
BtnContinue = "id = continue"
FinishTransaction = "id = back-to-products"
ErrorWarning = "class = error-message-container"