URL = "https://katalon-demo-cura.herokuapp.com"

BtnAppointment = "id = btn-make-appointment"
Username = "id = txt-username"
Password = "id = txt-password"
BtnLogin = "id = btn-login"
WrongCredential = "class = lead.text-danger"
Comment = "id = txt_comment"
Date = "id = txt_visit_date"
BtnBook = "id = btn-book-appointment"
readmission = "id = chk_hospotal_readmission"
CmbFclty = "id = combo_facility"